#pragma once

#define @PACKAGE_NAME_UPPER@_VERSION       "@PACKAGE_VERSION@"

#cmakedefine PACKAGE_VERSION_MAJOR
#ifdef PACKAGE_VERSION_MAJOR
#  define @PACKAGE_NAME_UPPER@_VERSION_MAJOR @PACKAGE_VERSION_MAJOR@
#else
#  define @PACKAGE_NAME_UPPER@_VERSION_MAJOR 0
#endif
#undef PACKAGE_VERSION_MAJOR

#cmakedefine PACKAGE_VERSION_MINOR
#ifdef PACKAGE_VERSION_MINOR
#  define @PACKAGE_NAME_UPPER@_VERSION_MINOR @PACKAGE_VERSION_MINOR@
#else
#  define @PACKAGE_NAME_UPPER@_VERSION_MINOR 0
#endif
#undef PACKAGE_VERSION_MINOR

#cmakedefine PACKAGE_VERSION_PATCH
#ifdef PACKAGE_VERSION_PATCH
#  define @PACKAGE_NAME_UPPER@_VERSION_PATCH @PACKAGE_VERSION_PATCH@
#else
#  define @PACKAGE_NAME_UPPER@_VERSION_PATCH 0
#endif
#undef PACKAGE_VERSION_PATCH

#cmakedefine PACKAGE_VERSION_TWEAK
#ifdef PACKAGE_VERSION_TWEAK
#  define @PACKAGE_NAME_UPPER@_VERSION_TWEAK @PACKAGE_VERSION_TWEAK@
#else
#  define @PACKAGE_NAME_UPPER@_VERSION_TWEAK 0
#endif
#undef PACKAGE_VERSION_TWEAK


#define @PACKAGE_NAME_UPPER@_TIMESTAMP     "@PACKAGE_TIMESTAMP@"
#define @PACKAGE_NAME_UPPER@_DATE          "@PACKAGE_DATE@"
#define @PACKAGE_NAME_UPPER@_TIME          "@PACKAGE_TIME@"
#define @PACKAGE_NAME_UPPER@_YEAR          @PACKAGE_YEAR@
