#pragma once

#define @PACKAGE_NAME_UPPER@_VERSION       "@PACKAGE_VERSION@"
#define @PACKAGE_NAME_UPPER@_VERSION_MAJOR @PACKAGE_VERSION_MAJOR@
#define @PACKAGE_NAME_UPPER@_VERSION_MINOR @PACKAGE_VERSION_MINOR@
#define @PACKAGE_NAME_UPPER@_VERSION_PATCH @PACKAGE_VERSION_PATCH@
#define @PACKAGE_NAME_UPPER@_VERSION_TWEAK @PACKAGE_VERSION_TWEAK@

#define @PACKAGE_NAME_UPPER@_TIMESTAMP     "@PACKAGE_TIMESTAMP@"
#define @PACKAGE_NAME_UPPER@_DATE          "@PACKAGE_DATE@"
#define @PACKAGE_NAME_UPPER@_YEAR          @PACKAGE_YEAR@
